?---
title: "Bayesian AB testing"
author: "Aurimas Racas"
date: '2022-12-05'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(scales)
library(pbapply)
library(HDInterval)
library(tolerance)
```

```{r}


generate_samples = function(base_rate, effect_size, n) {
  print(base_rate)
  tibble(
    A = rbinom(n=n, size=1, base_rate),
    B = rbinom(n=n, size=1, base_rate + effect_size)
  )
  
}

effect_size = 0.03
base_rate = 0.5
n = 1000

samples = generate_samples(base_rate=base_rate, effect_size=effect_size, n=n)


summary(samples)

```

```{r}

# prior for beta
alpha = 50
beta = 50

#prior for mean difference
mu = 0
sigma = 0.08
sigma = sqrt(2 * (alpha * beta) / ((alpha + beta) ** 2 * (alpha + beta + 1) ))

beta_posteriors = function(alpha, beta, data) {
  p_alpha = alpha + sum(data)
  p_beta = beta + length(data) - sum(data)
  mean = p_alpha / (p_alpha + p_beta)
  sd = sqrt((p_alpha * p_beta) / ((p_alpha + p_beta) ** 2 * (p_alpha + p_beta + 1) ))
  
  
  c(alpha=p_alpha, beta=p_beta, mean=mean, sd=sd)
}

norm_posteriors = function(mu, sigma, data) {
  sample_size = length(data)
  var_data = var(data)
  var_prior = sigma ** 2
  mean_data = mean(data)
  
  n_var_prior = sample_size * var_prior
  
  mu_posterior = (mu * var_data + n_var_prior * mean_data) / (var_data + n_var_prior)
  sigma_posterior = sqrt((var_prior * var_data) / (var_data + n_var_prior))
  
  c(mean=mu_posterior, sd=sigma_posterior)
}


posteriors = lapply(samples, function(d) beta_posteriors(alpha, beta, d))

posteriors$diff = norm_posteriors(mu, sigma, samples$B - samples$A)

```


```{r}
posteriors$diff
```

```{r}
sd(samples$B - samples$A) / sqrt(length(samples$A))
```


```{r}
print(quantile(rnorm(10000, posteriors$diff['mean'], posteriors$diff['sd']), c(0.025, 0.975)))

t.test(samples$B - samples$A)
```
```{r}
rbenchmark::benchmark(beta_diff(seq(-1,1,1000)))
```


```{r}

pdf_of_diffs = function(t, pdf_A, pdf_B) {
  f = function(i) pdf_A(i) * pdf_B(i-t)
  integrate(f, lower=0, upper=1)$value
}


#pdf_of_diffs = function(t, pdf_A, pdf_B) {
#  f = function(i) pdf_A(t+i) * pdf_B(i)
#  integrate(f, lower=-Inf, upper=Inf)$value
#}

norm_approx = function(x) dnorm(x, posteriors$diff['mean'], posteriors$diff['sd'])

beta_diff = function(x) {
  sapply(x, pdf_of_diffs,
    function(x) dbeta(x, posteriors$B['alpha'], posteriors$B['beta']),
    function(x) dbeta(x, posteriors$A['alpha'], posteriors$A['beta'])
    )
}


curve(beta_diff, from=-effect_size*1,to=2*effect_size, col='green', add=F, lty=c(5,1,9,20))
curve(norm_approx, from=-effect_size*1, to=2*effect_size, col='blue', add=T, lty='dashed')


```

```{r}
beta_diff_pdf = function(x, a1, b1, a2, b2) {
  
  A = beta(a1, b1) * beta(a2, b2)
  
  if ((x > 0) && (x <= 1)) {
    d = beta(a2, b1) * (x ** (b1 + b2 - 1)) * ((1 - x) ** (a2 + b1 - 1)) * 
      tolerance::F1(b1, a1 + b1 + a2 + b2 - 2, 1 - a1, b1 + a2, 1 - x, 1 - x ** 2) 
  }
  
  if ((x >= -1) && (x < 0)) {
    d = beta(a1, b2) * (-x ** (b1 + b2 - 1)) * ((1 + x) ** (a1 + b2 - 1)) * 
      tolerance::F1(b2, 1 - a2, a1 + b1 + a2 + b2 -2, a1 + b2, 1 - x ** 2, 1 + x)
  }
  
  
  if (x == 0) {
    d = beta(a1 + a2 - 1, b1 + b2 - 1)
  }
  
  return(d / A)
}

beta_diff_log_pdf = function(x, a1, b1, a2, b2) {
  A = lbeta(a1, b1) + lbeta(a2, b2)
  
  if ((x >= -1) && (x < 0)) {
    d = lbeta(a2, b1) + (x ** (b1 + b2 - 1)) * ((1 - x) ** (a2 + b1 - 1)) * 
      log(tolerance::F1(b2, 1 - a2, a1 + b1 + a2 + b2 -2, a1 + b2, 1 - x ** 2, 1 + x))
  }
  
  if ((x > 0) && (x <= 1)) {
    d = lbeta(a1, b2) + (x ** (b1 + b2 - 1)) * ((1 - x) ** (a1 + b2 - 1)) * 
      log(tolerance::F1(b1, a1 + b1 + a2 + b2 - 2, 1 - a1, b1 + a2, 1 - x, 1 - x ** 2))
      
  }
  
  if (x == 0) {
    d = beta(a1 + a2 - 1, b1 + b2 - 1)
  }
  
  return(d - A)
}


closed_form_pdf = function(x) {
  sapply(x, beta_diff_pdf, 
                          posteriors$B['alpha'],
                          posteriors$B['beta'],
                          posteriors$A['alpha'],
                          posteriors$A['beta'])
}

#
#pdfs_closed_form = sapply(seq(-1,1,0.01), beta_diff_pdf, 
#                          posteriors$B['alpha'],
#                          posteriors$B['beta'],
#                          posteriors$A['alpha'],
#                          posteriors$A['beta'])

#curve(closed_form_pdf, from=-1, to=1, col='red', add=F)
curve(beta_diff, from=-1,to=1, col='green', add=F, lty=c(5,1,9,20), ylim=c(0,30))
curve(norm_approx, from=-1, to=1, col='blue', add=T, lty='dashed')


```

```{r}

a = 10
b = 38
b.prime = -9
c = 20
x = 0.1

tolerance::F1(a, b, b.prime, c, 1 - x, 1 - x ** 2)

r = integrate(function (u) {
  u ** (a - 1) * 
    (1 - u) ** (c - a - 1) * 
    (1 - u * (1 - x)) ** (-b) * 
    (1 - u * (1 - x ** 2)) ** (-b.prime)
  }, lower=0, upper=1
)

r$value * gamma(c) / (gamma(a) * (gamma(c - a))) 


```

$$\tilde{Λ}_n = {\frac{2σ^2}{V_n + nτ^2}}\exp{≤ft(\frac{n^2τ^2(\bar{Y}_n $$


$$\tilde{Λ}_n = √{\frac{2σ^2}{V_n + nτ^2}}\exp{≤ft(\frac{n^2τ^2(\bar{Y}_n - \bar{X}_n-θ_0)^2}{4σ2(2σ^2+nτ^2)}\right)}$$


```{r}
generate_densities = function(posteriors) {
  
  sds = 5
  
  min_x = min(
      posteriors$A['mean'] - posteriors$A['sd'] * sds, 
      posteriors$B['mean'] - posteriors$B['sd'] * sds
  )
  
  max_x = max(
      posteriors$A['mean'] + posteriors$A['sd'] * sds, 
      posteriors$B['mean'] + posteriors$B['sd'] * sds
  )
  
  X = seq(from=min_x, to=max_x, length.out=10000)
  Ay = dbeta(X, shape1 = posteriors$A['alpha'], shape2 = posteriors$A['beta'])
  By = dbeta(X, shape1 = posteriors$B['alpha'], shape2 = posteriors$B['beta'])
  
  idx = max(which(diff(sign(Ay - By)) != 0),1)
  intersection = X[idx]
  
  expected_loss = (((Ay - By)[1:intersection]) %*% X[1:intersection])[1,1]
  
  list(
    data=tibble(x=X, A=Ay, B=By),
    intersection = intersection,
    prob_B_better = 1 - pbeta(
      intersection, 
      shape1 = posteriors$B['alpha'], 
      shape2 = posteriors$B['beta']
    ),
    prob_above_zero = 1 - pnorm(
      0, 
      posteriors$diff['mean'], 
      posteriors$diff['sd']
    ),
    expected_loss = expected_loss
  )
}


draw_distributions = function(densities, posteriors) {
  
  
  unpivoted = densities$data |> 
    pivot_longer(c(A, B), names_to='group', values_to = 'density')
  
  test_better = unpivoted |> filter((x >= densities$intersection) & (group == 'B'))
  
  unpivoted |>
    ggplot(aes(x=x, y=density, color=group, fill=group)) + 
    geom_line() + 
    geom_vline(xintercept=densities$intersection, linetype='dashed') +
    geom_area(data = test_better) + 
    annotate(
      x=quantile(densities$data$x, 0.75),
      y= max(densities$data$B) * 1.08,
      label=paste(
        "Prob that B is better:", 
        scales::percent(densities$prob_B_better, accuracy=0.1),
        "\n",
        "Prob that diff above zero: ", 
        scales::percent(densities$prob_above_zero, accuracy=0.1)
      ),
      size=3,
      geom='label'
    ) 
    
  
}

densities = generate_densities(posteriors) 

densities |> draw_distributions(posteriors)

```
```{r}

baseline = 0.42
effect_size = 0.02
sig_level = 0.05
power = 0.8

alpha = 420
beta = 1000 - 420
mu = 0
sigma = 1

sample_size = ceiling(
  power.prop.test(
    p1=baseline, 
    p2=baseline + effect_size, 
    sig.level=sig_level, 
    power=power
  )$n)


run_sim = function(
    baseline=0.42, 
    effect_size=0.02, 
    sample_size=10000, 
    alpha=1, 
    beta=1, 
    mu=0, 
    sigma=0.1, 
    sig_level=0.05,
    confidence = 0.95,
    min_effect = 0,
    width = NULL,
    cred_set = 0.95
) {
    if (is.null(width)) {
      width = effect_size / 4
    }
    results = mclapply(1:1000, function(i) {
      samples = generate_samples(baseline, effect_size, n=sample_size)
      pval = prop.test(
        x=apply(samples, 2, sum), 
        n=apply(samples, 2, length),
        alternative='two.sided')$p.value
      
      min_size_pval = t.test(samples$B, samples$A, mu=min_effect, alternative='greater')$p.value
        
      
      posteriors = lapply(samples, function(d) beta_posteriors(alpha, beta, d))
      posteriors$diff = norm_posteriors(mu, sigma, samples$B - samples$A)
      
      densities = generate_densities(posteriors)
      
      achieved_width = posteriors$diff['sd'] * -qnorm((1 - cred_set)/2) * 2
      
      list(
        p_val = coalesce(pval < sig_level, 0),
        min_size_pval = coalesce(min_size_pval < sig_level, 0),
        B_better = coalesce(densities$prob_B_better >= confidence, 0),
        diff_above = coalesce(densities$prob_above_zero >= confidence, 0),
        diff_above_size = coalesce(
          (1 - pnorm(
          min_effect, 
          posteriors$diff['mean'], 
          posteriors$diff['sd'])) >= confidence, 0
        ),
        below_width = coalesce(achieved_width <= width, 0),
        width = achieved_width,
        expected_loss = coalesce(densities$expected_loss, 0)
      )
    }, mc.cores=6)
    
    t = do.call(bind_rows, results)
    t |> apply(2, mean)
}

```


```{r}
`sigma_prior_results = pblapply(seq(-3, 0, 0.1), function(i) {
  sigma = 10 ** i
  c(list(i=sigma), run_sim(sigma=sigma))
}, cl=1)

do.call(bind_rows, sigma_prior_results) |> 
  ggplot() + geom_line(aes(x=i, y=diff_above), color='red') + ylim(0,1) +
  geom_line(aes(x=i, y=B_better), color='blue') +
  scale_x_log10()
```

```{r}
beta_prior_results = pblapply(seq(1, 10000, 500), function(i) {
  alpha = ceiling(i * baseline)
  beta = i - alpha
  c(list(i=i), run_sim(alpha=alpha, beta=beta))
}, cl=1)

do.call(bind_rows, beta_prior_results) |> 
  ggplot() + geom_line(aes(x=i, y=diff_above), color='red') + ylim(0,1) +
  geom_line(aes(x=i, y=B_better), color='blue')
```

```{r}
sample_size_results = pblapply(seq(1000, 10000, 500), function(i) {
  c(list(i=i), run_sim(sample_size = i))
}, cl=1)

do.call(bind_rows, sample_size_results) |> 
  ggplot() + geom_line(aes(x=i, y=diff_above), color='red') + ylim(0,1) +
  geom_line(aes(x=i, y=B_better), color='blue') + 
  geom_line(aes(x=i, y=p_val), color='green')
```
```{r}
sample_size_results = pblapply(seq(1000, 10000, 500), function(i) {
  c(list(i=i), run_sim(sample_size = i, confidence=0.8))
}, cl=1)

do.call(bind_rows, sample_size_results) |> 
  ggplot() + geom_line(aes(x=i, y=diff_above), color='red') + ylim(0,1) +
  geom_line(aes(x=i, y=B_better), color='blue') + 
  geom_line(aes(x=i, y=p_val), color='green')
```

```{r}
width_results = pblapply(seq(1000, 10000, 500), function(i) {
  c(list(i=i), run_sim(sample_size = i, cred_set=0.95))
}, cl=1)

do.call(bind_rows, width_results) |> 
  ggplot() + geom_line(aes(x=i, y=width), color='red') 
```
```{r}
width_results = pblapply(seq(1000, 10000, 500), function(i) {
  c(list(i=i), run_sim(sample_size = i, cred_set=0.95))
}, cl=1)

do.call(bind_rows, width_results) |> 
  ggplot() + geom_line(aes(x=i, y=expected_loss), color='red') 

```
```{r}
run_sim(sample_size = 5000)
```

